export type AccountDebitWebhookPayload = {
    eventType: 'account.debit';
    type: 'transfer';
    data: {
        queued: boolean;
        limitExceeded: boolean;
        _id: string;
        client: string;
        account: string;
        type: 'Outwards' | 'Inwards';
        sessionId: string;
        nameEnquiryReference: string;
        paymentReference: string;
        mandateReference: string | null;
        isReversed: boolean;
        reversalReference: string | null;
        provider: string;
        providerChannel: string;
        providerChannelCode: string;
        destinationInstitutionCode: string;
        creditAccountName: string;
        creditAccountNumber: string;
        creditBankVerificationNumber: string | null;
        creditKYCLevel: string;
        debitAccountName: string;
        debitAccountNumber: string;
        debitBankVerificationNumber: string | null;
        debitKYCLevel: string;
        transactionLocation: string;
        narration: string;
        amount: number;
        fees: number;
        vat: number;
        stampDuty: number;
        responseCode: string | null;
        responseMessage: string | null;
        status: string;
        recurringTransfer: string | null;
        isDeleted: boolean;
        createdAt: string;
        createdBy: string;
        updatedAt: string;
        __v: number;
    };
};